name: wifi_scanning_flutter
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# auto update dependencies by ctrl+shift+p -> pubspec assist -> (package name)
version: 1.0.0+1

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  wifi:
    path: ./wifi-master
  background_fetch: ^0.6.0
  carousel_slider: ^3.0.0
  cloud_firestore: ^1.0.0
  collection: ^1.14.13
  connectivity: ^3.0.2
  csv: ^4.1.0
  cupertino_icons: ^1.0.0
  equatable: ^1.2.5
  firebase_auth: ^1.0.0
  firebase_core: ^1.0.0
  firebase_core_platform_interface: ^4.0.0
  firebase_messaging: ^9.0.0
  flutter_bloc: ^6.1.1
  flutter_launcher_icons: ^0.9.0
  hexcolor: ^1.0.6
  hive_flutter: ^1.0.0
  http: ^0.13.0
  intl: ^0.17.0
  loading_animations: ^2.2.0
  lottie: ^1.0.0
  page_transition: ^1.1.7+2
  path_provider: ^2.0.1
  plugin_platform_interface: ^2.0.0
  provider: ^4.3.2+2
  sembast: ^2.4.8+1
  shared_preferences: ^2.0.5
  slide_countdown_clock: ^1.0.3
  sqflite: ^1.3.2+2
  tuple: ^1.0.3
  usage: ^3.4.2
  webview_flutter: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.11.1
  hive_generator: ^1.0.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/launcher_icons/heart-health-64.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/lottie/healthengine-generic-tickbox.json
    - assets/lottie/covid19.json
    - assets/lottie/covid-contact.json
    - assets/lottie/corona-virus-sick.json
    - assets/lottie/no-connection.json
    - assets/lottie/covid.json
    - assets/lottie/loading.json
    - assets/lottie/stop.json

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: MontserratRegular
      fonts:
        - asset: assets/fonts/MontserratRegular/Montserrat-Regular.ttf
        - asset: assets/fonts/MontserratRegular/Montserrat-Italic.ttf
          style: italic

    - family: MontserratBold
      fonts:
        - asset: assets/fonts/MontserratBold/Montserrat-SemiBold.ttf
        - asset: assets/fonts/MontserratBold/Montserrat-SemiBoldItalic.ttf
          style: italic

    - family: KingsCaslonDisplay
      fonts:
        - asset: assets/fonts/KingsCaslonDisplay/KingsCaslonDisplay.ttf
        - asset: assets/fonts/KingsCaslonDisplay/KingsCaslonDisplayItalic.ttf
          style: italic

    - family: KingsCaslonText
      fonts:
        - asset: assets/fonts/KingsCaslonText/KingsCaslon.ttf
        - asset: assets/fonts/KingsCaslonText/KingsCaslonItalic.ttf
          style: italic

    - family: KingsBureauGrot
      fonts:
        - asset: assets/fonts/KingsBureauGrot/KingsBureauGrot-FiveOne.ttf
        - asset: assets/fonts/KingsBureauGrot/KingsBureauGrot-FiveOneItal.ttf
          style: italic
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
